# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  wiki:
    build:
      context: .
      dockerfile: dev/docker-sqlite/Dockerfile
    networks:
      - wikinet
    ports:
      - "3000:3000"
    volumes:
      - .:/wiki
      - /wiki/node_modules

networks:
  wikinet:

volumes:
  db-data:
