blank_issues_enabled: false
contact_links:
  - name: Wiki.js Community Support
    url: https://github.com/Requarks/wiki/discussions?discussions_q=category%3A%22Help+%2F+Questions%22
    about: Please ask and answer questions here.
