# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: Developer
      SA_PASSWORD: W1kiJSR0cks!
    logging:
      driver: "none"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - wikinet
    ports:
      - "11433:1433"

  wiki:
    build:
      context: .
      dockerfile: dev/docker-mssql/Dockerfile
    depends_on:
      - db
    networks:
      - wikinet
    ports:
      - "3000:3000"
    volumes:
      - .:/wiki
      - /wiki/node_modules
    command: ["sh", "./dev/docker-mssql/init.sh"]

networks:
  wikinet:

volumes:
  db-data:
