# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:

  redis:
    image: redis:4-alpine
    ports:
      - "16379:6379"
    logging:
      driver: "none"
    networks:
      - wikinet

  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - wikinet
    ports:
      - "15432:5432"

  adminer:
    image: adminer:latest
    logging:
      driver: "none"
    networks:
      - wikinet
    ports:
      - "3001:8080"

  wiki:
    build:
      context: .
      dockerfile: dev/docker/Dockerfile
    depends_on:
      - db
      - redis
    networks:
      - wikinet
    ports:
      - "3000:3000"
    volumes:
      - .:/wiki
      - /wiki/node_modules
    command: ["sh", "./dev/docker/init.sh"]

networks:
  wikinet:

volumes:
  db-data:
